/**
 * DepDrift HTML Formatter
 * Formats dependency analysis results as HTML
 *
 * @module formatters/htmlFormatter
 */

'use strict';

const fs = require('fs');
const path = require('path');

/**
 * Format analysis results as HTML
 * @param {Object} results - Analysis results
 * @param {Object} options - Formatting options
 * @returns {string} HTML report
 */
function generateHtmlReport(results) {
  const template = `
<!DOCTYPE html>
<html>
<head>
  <title>DepDrift Analysis Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 2rem; }
    table { border-collapse: collapse; width: 100%; }
    th, td { padding: 8px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background-color: #f2f2f2; }
    .high { color: red; }
    .medium { color: orange; }
    .low { color: green; }
  </style>
</head>
<body>
  <h1>DepDrift Analysis Report</h1>
  <h2>Package Analysis</h2>
  <table>
    <thead>
      <tr>
        <th>Package</th>
        <th>Current Version</th>
        <th>Expected Version</th>
        <th>Drift Level</th>
        <th>Security Issues</th>
      </tr>
    </thead>
    <tbody>
      ${results.packages.map(pkg => `
        <tr>
          <td>${pkg.name}</td>
          <td>${pkg.currentVersion || 'N/A'}</td>
          <td>${pkg.expectedVersion || 'N/A'}</td>
          <td class="${getDriftClass(pkg.driftLevel)}">${pkg.driftLevel?.toFixed(2) || 'N/A'}</td>
          <td class="${getSecurityClass(pkg.vulnerabilities?.length || 0)}">${pkg.vulnerabilities?.length || 0}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
  
  <h2>Summary</h2>
  <p>Total Packages Analyzed: ${results.packages.length}</p>
  <p>Average Drift Level: ${calculateAverageDrift(results.packages)}</p>
  <p>Total Security Issues: ${calculateTotalSecurityIssues(results.packages)}</p>
  
  <footer>
    <p>Generated by DepDrift on ${new Date().toLocaleString()}</p>
  </footer>
</body>
</html>`;

  return template;
}

function getDriftClass(level) {
  if (level >= 0.8) return 'high';
  if (level >= 0.5) return 'medium';
  return 'low';
}

function getSecurityClass(count) {
  if (count > 0) return 'high';
  return 'low';
}

function calculateAverageDrift(packages) {
  const driftLevels = packages
    .map(pkg => pkg.driftLevel)
    .filter(level => typeof level === 'number');
  
  if (driftLevels.length === 0) return 'N/A';
  
  const average = driftLevels.reduce((sum, level) => sum + level, 0) / driftLevels.length;
  return average.toFixed(2);
}

function calculateTotalSecurityIssues(packages) {
  return packages.reduce((sum, pkg) => sum + (pkg.vulnerabilities?.length || 0), 0);
}

/**
 * Save HTML report to file
 * @param {Object} results - Analysis results
 * @param {string} filePath - Path to save the HTML report
 * @returns {Promise<void>}
 */
async function saveHtmlReport(results, filePath) {
  const fs = require('fs-extra');
  const html = generateHtmlReport(results);
  await fs.writeFile(filePath, html, 'utf8');
}

// Export functions
module.exports = {
  generateHtmlReport,
  saveHtmlReport
};
